# Generated by Django 5.0.3 on 2024-04-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(default='STFF2717', max_length=8, unique=True, verbose_name='Staff ID (Generated)')),
                ('staff_firstname', models.CharField(max_length=20, verbose_name='First Name')),
                ('staff_lastname', models.CharField(max_length=20, verbose_name='Last Name')),
                ('edu_qualification', models.CharField(max_length=30, null=True, verbose_name='Educational Qualification')),
                ('staff_job_department', models.CharField(max_length=30, verbose_name='Staff Department')),
                ('address', models.TextField(default='', verbose_name='Permanent Address')),
                ('staff_phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('staff_email', models.EmailField(blank=True, max_length=40, verbose_name='Email Address')),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to='staffs/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.CharField(default='MGSD2717', max_length=8, unique=True, verbose_name='Student ID (Genereated)')),
                ('firstname', models.CharField(max_length=20, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=20, verbose_name='Last Name')),
                ('faathername', models.CharField(max_length=20, verbose_name="Father's Name")),
                ('mothername', models.CharField(max_length=20, verbose_name="Mother's Name")),
                ('address', models.TextField(default='', verbose_name='Permanent Address')),
                ('guardian_phone', models.CharField(max_length=20, verbose_name='Guardian Phone Number')),
                ('student_phone', models.CharField(max_length=20, verbose_name='Student Phone Number')),
                ('student_email', models.EmailField(blank=True, max_length=40, verbose_name='Email Address (If any)')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='students/')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(default='TCHR2717', max_length=8, unique=True, verbose_name='Teacher ID (Generated)')),
                ('firstname', models.CharField(max_length=20, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=20, verbose_name='Last Name')),
                ('teacher_of_subject', models.CharField(max_length=30, verbose_name='Dedicated Subject')),
                ('last_graduated_degree', models.CharField(max_length=30, verbose_name='Last Graduation Degree')),
                ('last_graduated_subject', models.CharField(max_length=30, verbose_name='Subject of Graduation')),
                ('last_graduated_university', models.CharField(max_length=30, verbose_name='Graduated from University')),
                ('last_graduated_session', models.CharField(max_length=30, verbose_name='Session')),
                ('address', models.TextField(default='', verbose_name='Permanent Address')),
                ('teacher_phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('teacher_email', models.EmailField(max_length=40, verbose_name='Email Address')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='teachers/')),
            ],
        ),
    ]
