# Generated by Django 5.0.3 on 2024-04-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadminmanagement', '0002_alter_staffinfo_staff_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='faathername',
            new_name='fathername',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='Student_id',
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='staff_id',
            field=models.CharField(default='STFF2839', max_length=8, unique=True, verbose_name='Staff ID (Generated)'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher_id',
            field=models.CharField(default='TCHR2839', max_length=8, unique=True, verbose_name='Teacher ID (Generated)'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='student_id',
            field=models.CharField(default='MGSD751109', max_length=8, unique=True, verbose_name='Student ID -Genereated'),
        ),
    ]
