# Generated by Django 5.0.3 on 2024-04-28 22:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadminmanagement', '0003_rename_faathername_studentinfo_fathername_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_subject', models.CharField(max_length=255)),
                ('notice_body', ckeditor.fields.RichTextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='staff_id',
            field=models.CharField(default='STFF3853', max_length=8, unique=True, verbose_name='Staff ID (Generated)'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='student_id',
            field=models.CharField(default='MGSD720693', max_length=10, unique=True, verbose_name='Student ID -Genereated'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher_id',
            field=models.CharField(default='TCHR3853', max_length=8, unique=True, verbose_name='Teacher ID (Generated)'),
        ),
    ]
