# Generated by Django 5.0.3 on 2024-04-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadminmanagement', '0004_notice_alter_staffinfo_staff_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='publish_category',
            field=models.CharField(choices=[('2', 'Students'), ('5', 'Students & Teachers'), ('3', 'Teachers'), ('6', 'Staffs & Teachers'), ('7', 'Administrations'), ('1', 'All'), ('4', 'Staffs')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='staff_id',
            field=models.CharField(default='STFF5533', max_length=8, unique=True, verbose_name='Staff ID (Generated)'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='student_id',
            field=models.CharField(default='MGSD121803', max_length=10, unique=True, verbose_name='Student ID -Genereated'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher_id',
            field=models.CharField(default='TCHR5533', max_length=8, unique=True, verbose_name='Teacher ID (Generated)'),
        ),
    ]
