# Generated by Django 5.0.3 on 2024-04-22 23:51

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('classfor', models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('0', 'Add this book as new book ')], max_length=20)),
                ('subjectcode', models.IntegerField(default='1000')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stclass', models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5')], max_length=10)),
                ('assignment', ckeditor.fields.RichTextField()),
                ('publishdate', models.DateTimeField(auto_now_add=True)),
                ('activation', models.CharField(default='1', max_length=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectid', to='assignment.booklist')),
            ],
            options={
                'ordering': ['-publishdate'],
            },
        ),
    ]
