# Generated by Django 5.0.3 on 2024-04-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='subjectcode',
            field=models.IntegerField(),
        ),
    ]
